In [88]:
feature_map = np.array([
    [[1,2],[3,4]], #kênh 1
    [[5,6],[7,8]], #kênh 2
    [[9,10],[11,12]] #kênh 3
                        ])
feature_map.shape


(3, 2, 2)

In [125]:
#bài 1  cách 1
import numpy as np
def compute_gram_matrix(feature_map: np.ndarray) -> np.ndarray:
  C,H,W = feature_map.shape
  F = feature_map.reshape(C,H*W)
  G = [[0 for _ in range(3)] for _ in range(3)]
  G=np.zeros((C,C))
  for i in range(C):
    for j in range(C):
      G[i][j]=np.dot(F[i],F[j])/(H*W)

  return G
G=compute_gram_matrix(feature_map)
for i in range(len(G)):
  print(G[i])


[ 7.5 17.5 27.5]
[17.5 43.5 69.5]
[ 27.5  69.5 111.5]


In [108]:
#bài 1 cách 2
def compute_gram_matrix2(feature_map: np.ndarray) -> np.ndarray:
  C,H,W = feature_map.shape
  F = feature_map.reshape(C,H*W)
  G = [[0 for _ in range(3)] for _ in range(3)]
  G = [[sum(F[i][k] * F[j][k] for k in range(H * W)) for j in range(C)] for i in range(C)]
  #for i in range(C):
    #i=0[1,2,3,4]
    #row = []
    #for j in range(C):
      #j=0 [1,2,3,4]
      #sum_value= 0
      #k=0 [1] k =1 [1] k=2 [2] k=4 [3]
      #for k in range(H * W):
       # sum_value += F[i][k] * F[j][k]
      #row.append(sum_value/H*W)
      #print(f"  G[{i},{j}] = {G[i, j]}")
    #G.append(row)


  return G
G=compute_gram_matrix(feature_map)
for i in range(len(G)):
  print(G[i])


[ 7.5 17.5 27.5]
[17.5 43.5 69.5]
[ 27.5  69.5 111.5]


In [117]:
G

array([[  7.5,  17.5,  27.5],
       [ 17.5,  43.5,  69.5],
       [ 27.5,  69.5, 111.5]])

In [120]:
#bài 2
feature_map1 =  np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
                        ])
feature_map2 =  np.array([
    [[2,4],[6,8]],
    [[1,3],[5,7]],
    [[0,2],[4,6]]
                        ])

In [137]:
#cách 2
def compute_similarity(gram1:np.ndarray,gram2:np.ndarray)->float:
  numerator = np.trace(np.dot(gram1, gram2))
  denominator = np.linalg.norm(gram1) * np.linalg.norm(gram2)
  return numerator / denominator



gram1 = compute_gram_matrix(feature_map1)
gram2 = compute_gram_matrix(feature_map2)
similarity = compute_similarity(gram1 , gram2)
print(similarity)

0.6741245785155123


In [136]:
#cách 2
def compute_similarity2(gram1:np.ndarray,gram2:np.ndarray)->float:
  numerator = 0
  for i in range(len(gram1)):
    for j in range(len(gram1[0])):
      numerator += gram1[i][j] * gram2[i][j]

  norm1 = 0
  norm2 = 0
  for i in range(len(gram1)):
    for j in range(len(gram1[0])):
      norm1 += gram1[i][j] ** 2
      norm2 += gram2[i][j] ** 2
      demonirator = np.sqrt(norm1 * norm2)
  return numerator/demonirator


gram1 = compute_gram_matrix(feature_map1)
gram2 = compute_gram_matrix(feature_map2)
similarity = compute_similarity2(gram1 , gram2)
print(similarity)

0.6741245785155123
