In [1]:
import tensorflow as tf

In [2]:
tensor = tf.constant([[1,2],[3,4]])

In [3]:
print(f"Shape:",tensor.shape)
print(f"dtype:",tensor.dtype)
print(f"rank", tensor.ndim)

Shape: (2, 2)
dtype: <dtype: 'int32'>
rank 2


In [6]:
zeros = tf.zeros([2,3])
ones = tf.ones([3,2])
print(zeros)
print(ones)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [7]:
random = tf.random.normal([2,2], mean=0,stddev=1.0)
print(random)

tf.Tensor(
[[ 0.35818106  1.1760256 ]
 [-0.22037558  1.42958   ]], shape=(2, 2), dtype=float32)


In [9]:
float_tensor = tf.constant([1.0,2.0])
int_tensor = tf.cast(float_tensor,tf.int32)
print(int_tensor)

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [11]:
tensor = tf.constant([[1,2,3],[4,5,6]])
elem = tensor[1,2]
print(elem)

slice = tensor[:,1:]
print(slice)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)


##khởi tạo tensor toàn giá trị 5##

In [14]:
tensor = tf.constant(5,shape=(3,4))
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])>

In [15]:
tensor = tf.random.normal((2,2,2),mean=0 , stddev=1)
print(tensor)

tf.Tensor(
[[[-0.41948617  0.6532199 ]
  [ 0.15681843  0.66176   ]]

 [[-0.36483073  0.67505115]
  [-0.8170817  -0.19943392]]], shape=(2, 2, 2), dtype=float32)


In [19]:
x = [1,2,3,4]
diag = tf.linalg.diag(x)
print(diag)

tf.Tensor(
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]], shape=(4, 4), dtype=int32)


In [20]:
tensor = tf.constant([[1,2,3,4],
                      [5,6,7,8],
                      [9,10,11,12]])
tensor[::2,:]

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])>

In [21]:
tensor[:,1:2]

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 2],
       [ 6],
       [10]])>

In [27]:
tensor[0:2,2:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [7, 8]])>

In [32]:
reshape=tf.reshape(tensor,(4,3))
reshape

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [34]:
a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[5,6],
                 [7,8]])
c=2*a+b
print(c)

tf.Tensor(
[[ 7 10]
 [13 16]], shape=(2, 2), dtype=int32)


In [36]:
dot_product = tf.tensordot(a,b,axes=2)
print(dot_product)

tf.Tensor(70, shape=(), dtype=int32)


In [39]:
det_a = tf.linalg.det(tf.cast(a,dtype=tf.float32))
print(det_a)

tf.Tensor(-2.0, shape=(), dtype=float32)


In [40]:
transpose_a = tf.transpose(a)
print(transpose_a)


tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
