### Increate brightness

In [12]:
data = np.array([-4, 3, 8, 300, 7])
print(data)

data = np.clip(data, 0, 255)
print(data)

[ -4   3   8 300   7]
[  0   3   8 255   7]


In [8]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.png', 1)
img = img.astype(float)

img = img + 50
img = np.clip(img, 0, 255)

img = img.astype(np.uint8)
cv2.imwrite('increase50_clip.png', img)

True

In [19]:
data = np.array([-4., 3, 8, 300, 7])
print(data)
print(data.dtype)

data = np.where(data<0, 0, data)
print(data)

data = np.where(data>255, 255, data)
print(data)

[ -4.   3.   8. 300.   7.]
float64
[  0.   3.   8. 300.   7.]
[  0.   3.   8. 255.   7.]


In [23]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.png', 1)
img = img.astype(float)

img = img + 50
img = np.where(img<0., 0., img)
img = np.where(img>255., 255., img)

img = img.astype(np.uint8)
cv2.imwrite('increase50_where.png', img)

float64


True

### Decrease brightness

In [24]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.png', 1)
img = img.astype(float)

img = img - 80
img = np.clip(img, 0, 255)

img = img.astype(np.uint8)
cv2.imwrite('decrease80_clip.png', img)

True

In [25]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.png', 1)
img = img.astype(float)

img = img - 80
img = np.where(img<0., 0., img)
img = np.where(img>255., 255., img)

img = img.astype(np.uint8)
cv2.imwrite('decrease80_where.png', img)

True

### Crop a region

In [1]:
import cv2
import numpy as np

img = cv2.imread('image.png', 1)
height, width, channel = img.shape

x_0, y_0 = 470, 120
x_1, y_1 = 800, 850

region = img[y_0:y_1, x_0:x_1, :]
cv2.imwrite('output_region.png', region)

True