In [ ]:
import numpy as np

In [ ]:
A= np.array ([[1,2],[3,4]])
B= np.array ([[5,6],[7,8]])

C=A+B
D=A-B

print(C)
print(D)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [ ]:
C= np.array ([[2,-3],[4,-5]])
D= np.array ([[1,4],[-2,6]])

E=C+D
F=C-D

print(E)
print(F)

[[3 1]
 [2 1]]
[[  1  -7]
 [  6 -11]]


In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

E=A*B
print(E)


[[ 5 12]
 [21 32]]


In [ ]:
A=np.array([[0,1,2],[3,4,5]])
B=np.array([[5,4,3],[2,1,0]])

E=A*B
print(E)

[[0 4 6]
 [6 4 0]]


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
np.dot(A,B)

32

In [ ]:
def convolution(A,B):
  n_rows = len(A)-len(B)+1
  n_cols= len(A) - len(B) +1

  if n_rows <= 0 and n_cols <= 0:
    return []
  result =[]
  for i in range(n_rows):
    row = []
    for j in range(n_cols):
      sum = 0
      for rows in range(len(B)):
        for cols in range(len(B[0])):
          sum += A[i+rows][j+cols] * B[rows][cols]
      row.append(sum)
    result.append(row)
  return result

A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,0],[0,-1]])
output= convolution(A,B)
print(output)

[[-4, -4], [-4, -4]]


In [43]:
import numpy as np
def rotator_vector(v1,degree):
  R=np.array([
            [np.cos(degree),-np.sin(degree)],
             [np.sin(degree),np.cos(degree)]
              ])
  output = np.dot(v1,R)
  return output
v1=np.array([1,0])
degree=45
print(rotator_vector(v1,degree))

[ 0.52532199 -0.85090352]
