In [1]:
import numpy as np

In [7]:
#maskbooling
arr = np.array([1,-2,3,-4,5,-6])
arr[arr < 0]=0
arr

array([1, 0, 3, 0, 5, 0])

In [10]:
arr2 = np.array([1,2,4,-4,-3,-2])
arr2 = np.where( arr2 < 0 , 0 , arr2)
arr2

array([1, 2, 4, 0, 0, 0])

In [13]:
arr3 = np.array([1,2,4,-4,-3,-2])
arr3 = np.where(arr2 % 2 ,"even","odd")
arr3

array(['even', 'odd', 'odd', 'odd', 'odd', 'odd'], dtype='<U4')

In [14]:
# Tìm vị trí các phần tử lớn hơn 2
positions = np.where(arr2 > 2)

positions


(array([2], dtype=int64),)

In [15]:
temps = np.array([25,28,30,22,35,18,20])


In [18]:
conditions =[
    temps < 20 ,
    (temps >=20) & (temps<30),
    temps >=30
]
choices = ['Cold','Mild', 'Hot']
categories = np.select(conditions, choices, default='Unknown')
categories

array(['Mild', 'Mild', 'Hot', 'Mild', 'Hot', 'Cold', 'Mild'], dtype='<U7')

In [20]:
mat = np.random.randint(1,100,(5,5))
mat

array([[17, 13, 64, 16, 40],
       [86, 20, 86, 71, 79],
       [98, 34,  3, 38, 26],
       [22, 42,  4, 24, 45],
       [41, 55, 38, 11, 39]])

In [21]:
row_min = mat.min(axis=1, keepdims= True)
row_max = mat.max(axis=1, keepdims= True)
normalizaed_mat = (mat - row_min) / (row_max - row_min)
normalizaed_mat

array([[0.07843137, 0.        , 1.        , 0.05882353, 0.52941176],
       [1.        , 0.        , 1.        , 0.77272727, 0.89393939],
       [1.        , 0.32631579, 0.        , 0.36842105, 0.24210526],
       [0.43902439, 0.92682927, 0.        , 0.48780488, 1.        ],
       [0.68181818, 1.        , 0.61363636, 0.        , 0.63636364]])

In [23]:
arr = np.random.rand(2,3,4)
arr

array([[[0.35764788, 0.08293857, 0.36017291, 0.76463393],
        [0.31743705, 0.80709733, 0.79980125, 0.48956439],
        [0.12029413, 0.9793139 , 0.69974135, 0.991093  ]],

       [[0.63855874, 0.35678136, 0.74849889, 0.21793483],
        [0.06417996, 0.34193374, 0.22054058, 0.05057884],
        [0.70973093, 0.20160373, 0.40639123, 0.17776848]]])

In [36]:
arr.shape[1]

3

In [35]:
arr.shape[0]

2

In [37]:
arr.shape[2]

4

In [38]:
mat = np.random.randint(1,100,(5,5))
e_x = np.exp(mat)
softmax_col = e_x / e_x.sum(axis=0, keepdims= True
                            )


In [40]:
print(mat)

[[28 30 38 13 22]
 [75 41 56 50 69]
 [54 51 22 50 70]
 [ 6 82 60 48 68]
 [19 19 72 40 65]]


In [41]:
print(softmax_col)

[[3.87399763e-21 2.61027907e-23 1.71389771e-15 3.99603110e-17
  9.43846857e-22]
 [9.99999999e-01 1.56288219e-18 1.12534471e-07 4.68300574e-01
  2.43636405e-01]
 [7.58256042e-10 3.44247711e-14 1.92873778e-22 4.68300574e-01
  6.62272414e-01]
 [1.08063928e-30 1.00000000e+00 6.14417391e-06 6.33775908e-02
  8.96288247e-02]
 [4.78089288e-25 4.35961000e-28 9.99993743e-01 2.12608132e-05
  4.46235642e-03]]


In [42]:
pixel = np.random.randint(0,256,(4,4))
pixel

array([[ 96, 119,  57,   6],
       [ 26, 230,  88, 202],
       [ 14, 241, 142,  55],
       [106, 255,  81,   8]])

In [48]:
def adjust_constrast(chanel):
    return np.clip(chanel * 1.5,0,255)
enhanced = np.apply_along_axis(adjust_constrast,1,pixel)
#axist=1

In [49]:
enhanced

array([[144. , 178.5,  85.5,   9. ],
       [ 39. , 255. , 132. , 255. ],
       [ 21. , 255. , 213. ,  82.5],
       [159. , 255. , 121.5,  12. ]])

In [50]:
data = np.array([
    [1,2,np.nan],
    [4,np.nan,6],
    [7,8,9]
])
data

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [55]:
filtered = np.where(np.isnan(data[:,0]),np.nanmean(data[:,0]),data[:,0])

In [56]:
filtered

array([1., 4., 7.])

In [57]:
mean_pixel = np.mean(pixel)
std_pixel = np.std(pixel)

# Calculate Z-score for each element
z_score = (pixel - mean_pixel) / std_pixel
z_score

array([[-0.14524856,  0.13607497, -0.62227542, -1.24607978],
       [-1.00145062,  1.4937668 , -0.24310023,  1.15128598],
       [-1.14822811,  1.62831284,  0.4173985 , -0.64673834],
       [-0.02293398,  1.79955325, -0.32872043, -1.22161686]])

In [58]:
pixel_min = np.min(pixel)
pixel_max = np.max(pixel)
scaled_pixel = (pixel - pixel_min) / (pixel_max - pixel_min)

scaled_pixel

array([[0.36144578, 0.45381526, 0.20481928, 0.        ],
       [0.08032129, 0.89959839, 0.32931727, 0.78714859],
       [0.03212851, 0.9437751 , 0.54618474, 0.19678715],
       [0.40160643, 1.        , 0.30120482, 0.00803213]])

In [59]:
# Mảng các phần tử cần kiểm tra
arr = np.array([1, 2, 3, 4, 5])

# Mảng các phần tử kiểm tra sự tồn tại
check = np.array([3, 6, 1])

# Kiểm tra xem các phần tử của arr có tồn tại trong check không
result = np.isin(arr, check)

print(result)


[ True False  True False False]
