In [1]:
import numpy as np
import pandas as pd


In [7]:
data = np.array([2,3,5,7,7])
data


[2, 3, 5, 7, 7]

list dynamic

In [21]:
array2 = np.zeros((2,3))
array3 = np.ones((2,3))

array4 = np.full((2, 3), fill_value=7)  # Tạo mảng có kích thước (7,2,3) với giá trị 0
array4
array5=np.linspace(0,1,5)
array5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
array6 = np.arange(0, 10, 2)  # Dùng np.arange thay vì np.range
print(array6)


[0 2 4 6 8]


In [1]:
import numpy as np
A = np.array([[3, 2], [1, 4]])  # Đúng cú pháp
det_A = np.linalg.det(A)  # Tính định thức
print(det_A)


10.000000000000002


In [3]:
A_inv = np.linalg.inv(A)
print(A_inv)


[[ 0.4 -0.2]
 [-0.1  0.3]]


In [4]:
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
x = np.linalg.solve(A, b)
print(x)  # Kết quả: [3. 4.]


[2.2 3.6]


In [5]:
v = np.array([3, 4])
norm_v = np.linalg.norm(v)
print(norm_v)  # Kết quả: 5.0 (Vì 3-4-5 là tam giác vuông)


5.0


In [7]:
i=np.empty((2,3))
i

array([[5.39845192e+242, 5.98129679e-154, 3.44210253e+175],
       [1.15938461e-012, 1.13901975e-094, 8.65022201e-013]])

In [37]:
h= np.eye(3)
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
arr = np.array(["hello",1.0,None,5.0,True])
for x in arr:
    print(type(x),end=" ")

<class 'str'> <class 'float'> <class 'NoneType'> <class 'float'> <class 'bool'> 

In [13]:
arr = np.array([3,1.0,2,5.0,4])
for x in arr:
    print(type(x),end=" ")

<class 'numpy.float64'> <class 'numpy.float64'> <class 'numpy.float64'> <class 'numpy.float64'> <class 'numpy.float64'> 

dictionary là một kiểu object 
float 8 - 32- 64 để tránh ý nghĩa của số thập phân có ý nghĩa 


In [15]:
arr = np.array([3,1,2,5,4])
#adding elenemtn 
arr_add = np.append(arr, [9,9])
arr_add

array([3, 1, 2, 5, 4, 9, 9])

In [16]:
arr_del=np.delete(arr,2)
arr_del

array([3, 1, 5, 4])

In [17]:
arr_sort = np.sort(arr)
arr_sort

array([1, 2, 3, 4, 5])

In [18]:
# trả về danh sách index dựa vào ds này để sắp xếp mãng 
arr_argsort = np.argsort(arr)
arr_argsort

array([1, 2, 0, 4, 3], dtype=int64)

In [19]:
arr2d = np.array([[4,2],[3,1]])
arr2d_sort = np.sort(arr2d)
arr2d_sort

array([[2, 4],
       [1, 3]])

In [20]:
arr2d_sort_dim0 = np.sort(arr2d,axis=0) #argument chiều axis = 0 
arr2d_sort_dim0

array([[3, 1],
       [4, 2]])

In [21]:
sorted_arr = np.array([1,3,5,7,9])
values = [2,6]
indices = np.searchsorted(sorted_arr,values)
indices

array([1, 3], dtype=int64)

In [23]:
np.insert(sorted_arr,indices,values)

array([1, 2, 3, 5, 6, 7, 9])

In [24]:
#lexsort
#trả về index cái thứ 2 tuân theo cái đầu tiên 
names =np.array(['bob','alice','charlie','bob'])
ages = np.array([25,30,35,26])
lex_indices = np.lexsort((ages,names))
print(lex_indices)

[1 0 3 2]


In [25]:
print("lexsor result:",(names[lex_indices]))
ages[lex_indices]

lexsor result: ['alice' 'bob' 'bob' 'charlie']


array([30, 25, 26, 35])

In [36]:
ds = [11, 22, 33, 44, 55]
indices = [3, 2, 4, 0, 1]

# Sử dụng list comprehension để duyệt qua các chỉ số trong indices
print([ds[i] for i in indices])


[44, 33, 55, 11, 22]


In [35]:
import numpy as np

ds = np.array([11, 22, 33, 44, 55])
indices = [3, 2, 4, 0, 1]
print(ds[indices])


[44 33 55 11 22]


latex $x$ viết công thức toán học  ký hiệu của scalar
1vector sẽ chứa nhiều scalar
$\mathbf{x}$
1D(x,)
2D(x,y)
3D(c,x,y) đếm ngoặc vuông xác định số chiều 
X,y X đại diện cho ma trix y đại diện cho vector
$\mathcal{x}$ 3D trong latex

In [38]:
arr

array([3, 1, 2, 5, 4])

In [43]:
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.size)

2
(2, 2)
4


In [44]:
import numpy as np

# 1. Scalar (số vô hướng)
scalar = np.array(5)
print("Scalar:")
print("Shape:", scalar.shape)
print("ndim:", scalar.ndim)
print("Size:", scalar.size)
print()

# 2. 1D Vector
vector_1d = np.array([1, 2, 3])
print("1D Vector:")
print("Shape:", vector_1d.shape)
print("ndim:", vector_1d.ndim)
print("Size:", vector_1d.size)
print()

# 3. 2D Matrix
matrix_2d = np.array([[1, 2], [3, 4], [5, 6]])
print("2D Matrix:")
print("Shape:", matrix_2d.shape)
print("ndim:", matrix_2d.ndim)
print("Size:", matrix_2d.size)


Scalar:
Shape: ()
ndim: 0
Size: 1

1D Vector:
Shape: (3,)
ndim: 1
Size: 3

2D Matrix:
Shape: (3, 2)
ndim: 2
Size: 6


In [49]:
vector_1d.shape

(3,)

In [59]:
#length mới và length sau = nhau 
# Mảng 1D
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# In shape của mảng 1D
print("Shape của mảng 1D:", arr_1d.shape)

# Reshape thành 2D (2x3)
arr_2d = arr_1d.reshape(2, 3)

# In shape của mảng 2D
print("Shape của mảng 2D:", arr_2d.shape)

# In kết quả
print("Reshape 1D thành 2D (2x3):")
print(arr_2d)
arr_2d[0]


Shape của mảng 1D: (6,)
Shape của mảng 2D: (2, 3)
Reshape 1D thành 2D (2x3):
[[1 2 3]
 [4 5 6]]


array([1, 2, 3])

In [60]:


# Mảng 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# In shape của mảng 2D
print("Shape của mảng 2D:", arr_2d.shape)

# Reshape thành 3D (2x3x1)
arr_3d = arr_2d.reshape(2, 3, 1)

# In shape của mảng 3D
print("Shape của mảng 3D:", arr_3d.shape)

# In kết quả
print("Reshape 2D thành 3D (2x3x1):")
print(arr_3d)


Shape của mảng 2D: (2, 3)
Shape của mảng 3D: (2, 3, 1)
Reshape 2D thành 3D (2x3x1):
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [64]:
X = np.array ([[4,2],
               [3,1]])
X_tranpose = X.T
#X_tranpose = np.transpose(X)
print(X_tranpose)


[[4 3]
 [2 1]]


In [66]:
X1 = np.array ([[4,2],
               [3,1]])
X1_tranpose = X1.T
X1_tranpose

array([[4, 3],
       [2, 1]])

In [68]:
X_flip= np.flip(X)
X_flip

array([[1, 3],
       [2, 4]])

In [71]:
X_flatten=X.flatten()
print(X_flatten)

[4 2 3 1]


1 số là idexing data [0] 
2 số là slicing data [2:1]

In [72]:
#conditional Slicing
# Tạo mảng 3D với kích thước (3, 3, 3)
arr_3d = np.array([[[10, 20, 30], [40, 50, 60], [70, 80, 90]],
                   [[15, 25, 35], [45, 55, 65], [75, 85, 95]],
                   [[18, 28, 38], [48, 58, 68], [78, 88, 98]]])

# Lọc các phần tử lớn hơn 50
filtered_arr_3d = arr_3d[arr_3d > 50]

print("Mảng 3D ban đầu:")
print(arr_3d)
print("\nPhần tử lớn hơn 50:")
print(filtered_arr_3d)


Mảng 3D ban đầu:
[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[15 25 35]
  [45 55 65]
  [75 85 95]]

 [[18 28 38]
  [48 58 68]
  [78 88 98]]]

Phần tử lớn hơn 50:
[60 70 80 90 55 65 75 85 95 58 68 78 88 98]


In [73]:


# Mảng 2D có kích thước (3, 2)
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])

# Mảng 1D có kích thước (3,)
arr_1d = np.array([7, 8, 9])

# Kết hợp theo chiều ngang (axis=1)
result = np.column_stack((arr_2d, arr_1d))

print("Mảng 2D:")
print(arr_2d)
print("\nMảng 1D:")
print(arr_1d)
print("\nKết quả sau khi kết hợp:")
print(result)


Mảng 2D:
[[1 2]
 [3 4]
 [5 6]]

Mảng 1D:
[7 8 9]

Kết quả sau khi kết hợp:
[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [74]:
import numpy as np
# Mảng 2D với kích thước (3, 2)
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])

# Mảng 1D với kích thước (3,)
arr_1d = np.array([7, 8, 9])

# Kết hợp theo chiều ngang (axis=1) sử dụng np.concatenate
result = np.concatenate((arr_2d, arr_1d.reshape(-1, 1)), axis=1)

print("Mảng 2D:")
print(arr_2d)
print("\nMảng 1D:")
print(arr_1d)
print("\nKết quả sau khi kết hợp theo chiều ngang:")
print(result)

#axis = 1 concat hàng , hoặc là vector


Mảng 2D:
[[1 2]
 [3 4]
 [5 6]]

Mảng 1D:
[7 8 9]

Kết quả sau khi kết hợp theo chiều ngang:
[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [77]:
import numpy as np

# Mảng 1D với 6 phần tử
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape thành mảng 2D với số cột là 3
arr_2d = arr_1d.reshape(-1, 3)

print(arr_2d)


[[1 2 3]
 [4 5 6]]


In [75]:


# Mảng 2D với kích thước (2, 3)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Mảng 1D với kích thước (3,)
arr_1d = np.array([7, 8, 9])

# Chuyển mảng 1D thành mảng 2D với kích thước (1, 3)
arr_1d_2d = arr_1d.reshape(1, -1)

# Kết hợp theo chiều dọc (axis=0) sử dụng np.concatenate
result = np.concatenate((arr_2d, arr_1d_2d), axis=0)

print("Mảng 2D:")
print(arr_2d)
print("\nMảng 1D:")
print(arr_1d)
print("\nKết quả sau khi kết hợp theo chiều dọc:")
print(result)


Mảng 2D:
[[1 2 3]
 [4 5 6]]

Mảng 1D:
[7 8 9]

Kết quả sau khi kết hợp theo chiều dọc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


OPEN CV

In [80]:
%pip install opencv-python


Note: you may need to restart the kernel to use updated packages.


In [78]:
import cv2

In [82]:
from google.colab import files
import cv2

# Tải tệp lên
upload = files.upload()

# Lấy tên tệp từ dictionary
path = list(upload.keys())[0]
print(upload.keys())  # In ra danh sách các tệp đã tải lên

# Đọc hình ảnh với cv2
image = cv2.imread(path)

# Kiểm tra hình ảnh đã được tải chưa
if image is not None:
    # Hiển thị hình ảnh
    cv2.imshow("Uploaded Image", image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Không thể tải hình ảnh.")


ModuleNotFoundError: No module named 'google'