scaler $x$ , 
vector $\mathbf{x}\
matrix
tensor

xác định số chiều đếm từ ngoài vào trong 


In [2]:
import numpy as np 


type casting --> ép kiểu 

In [5]:
a = 2 
type(a)

int

In [6]:
int("2")

2

torch value , dtype và device những torch kiểu object giống dictionary chứa rất nhiều thông tin 
muốn đổi type thì tensor.type(torch.float16)
exponential - windown  , mantissa - offset
8bit lưu trử thông tin của cái cửa sổ exponential từ 2-4[2, 2.2 , 2.4 , 2.6 , 2.8,3.0,3.2...4.0] offset vị trí thực sự của số đó là bao nhiêu vd sô 3.14 thì lưu ỡ vị trí 7 [3.2] 

exponential 1. * 2 còn bias là 2^   (số bit exponentail - 1)

Uniform distribution Phân bố đều trên một khoảng (tất cả giá trị trong khoảng có xác suất như nhau)
Normal distribution - Gaussian Distribution Phân bố theo dạng chuông, tập trung quanh giá trị trung bình
sampling là lấy ngẫu nhiên ví dụ (100,100) là sampling 10.000 lần 

In [5]:
import torch
import matplotlib.pyplot as plt 

In [3]:
print(torch.__version__)

2.5.1


In [8]:
x = torch.FloatTensor(2, 3).uniform_(-1, -1)

In [9]:
print(x)

tensor([[-1., -1., -1.],
        [-1., -1., -1.]])


In [6]:
A = torch.randn(2,3,4)

In [9]:
A

tensor([[[ 1.9466,  0.5201, -1.1046,  0.8111],
         [-1.7989,  0.6046,  0.4935, -0.5972],
         [-1.1408,  0.5975, -0.4469, -1.6607]],

        [[ 2.0157,  1.1340,  0.9417,  0.8353],
         [-0.8929, -0.2156, -0.3469, -0.8762],
         [-0.9052, -0.1748, -0.6385, -1.5511]]])

In [7]:
A[:1,:2,:1]

tensor([[[ 1.9466],
         [-1.7989]]])

In [8]:
A[:1][:2][:1]

tensor([[[ 1.9466,  0.5201, -1.1046,  0.8111],
         [-1.7989,  0.6046,  0.4935, -0.5972],
         [-1.1408,  0.5975, -0.4469, -1.6607]]])