In [1]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else"cpu")


In [24]:
A= torch.arange(12,device=device).reshape(3,4).float()
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], device='cuda:0')

In [25]:
A.add(5) #broadcasting cộng thêm các phần tử thêm 5 

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]], device='cuda:0')

In [26]:
A.mul_(2) # nhân đôi các phần tử 

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.]], device='cuda:0')

In [28]:
print(A.sum(dim=1))


tensor([12., 44., 76.], device='cuda:0')


In [15]:
print(A.max(dim=0,keepdim=True))

torch.return_types.max(
values=tensor([[16., 18., 20., 22.]], device='cuda:0'),
indices=tensor([[2, 2, 2, 2]], device='cuda:0'))


In [16]:
#A = torch.tensor([[1,2,3],[4,5,6]])
#print(A.sum(dim=0))  # tensor([5,7,9]) — tổng theo từng cột
#print(A.max(dim=0).values)  # tensor([4,5,6]) — max theo từng cột

#print(A.sum(dim=1))  # tensor([6,15]) — tổng theo từng hàng
#print(A.max(dim=1).values)  # tensor([3,6]) — max theo từng hàng


tensor([5, 7, 9])
tensor([4, 5, 6])
tensor([ 6, 15])
tensor([3, 6])


In [2]:
G=torch.rand((5,5),device=device)
G

tensor([[0.5033, 0.7675, 0.8691, 0.7647, 0.9539],
        [0.0690, 0.9999, 0.4515, 0.8832, 0.3912],
        [0.7601, 0.1352, 0.8095, 0.7713, 0.0753],
        [0.9444, 0.3688, 0.6565, 0.5891, 0.3419],
        [0.9227, 0.8344, 0.9613, 0.3703, 0.9702]], device='cuda:0')

In [33]:
mask = G>0.5
print(mask)
print(G[mask])

tensor([[ True, False,  True, False,  True],
        [ True,  True, False,  True,  True],
        [False,  True, False, False,  True],
        [ True, False,  True,  True, False],
        [False,  True,  True, False,  True]], device='cuda:0')
tensor([0.5186, 0.8716, 0.9514, 0.7488, 0.6929, 0.7738, 0.7263, 0.8170, 0.9350,
        0.6947, 0.6761, 0.8823, 0.9483, 0.8785, 0.9404], device='cuda:0')


In [2]:
G = torch.rand((5,5))
result = torch.where(G > 0.5, G, torch.zeros_like(G))
result


tensor([[0.0000, 0.9722, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.8709, 0.7453],
        [0.6575, 0.5138, 0.0000, 0.5660, 0.5583],
        [0.0000, 0.0000, 0.0000, 0.8643, 0.0000],
        [0.5488, 0.5185, 0.5983, 0.8257, 0.6935]])

In [3]:
result = torch.where(G>0,G,torch.zeros_like(G))
result1 = torch.where(G<0 , G , torch.ones_like(G))

In [4]:
result

tensor([[0.5033, 0.7675, 0.8691, 0.7647, 0.9539],
        [0.0690, 0.9999, 0.4515, 0.8832, 0.3912],
        [0.7601, 0.1352, 0.8095, 0.7713, 0.0753],
        [0.9444, 0.3688, 0.6565, 0.5891, 0.3419],
        [0.9227, 0.8344, 0.9613, 0.3703, 0.9702]], device='cuda:0')

In [8]:
result1

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

In [4]:
Index = torch.tensor((0,1,2,3,4),device=device)
#result = torch.gather(input=G,dim=0,index=Index)

In [13]:
data = G.view(1,5,5)

torch.Size([5, 5])


In [18]:
print(Index.shape)

torch.Size([5])


In [20]:
G = torch.rand((5,5))
print(G)
col_indices = torch.tensor([4,3,2,1,0])       # shape (5,)
col_indices = col_indices.unsqueeze(1)  
print(col_indices)      # shape (5,1)

result = torch.gather(G, dim=1, index=col_indices)

print("Shape của result:", result.shape)      # (5,1)
print(result)
for i in range(G.shape[0]):
    row = i
    col = col_indices[i,0].item()
    val = G[row, col].item()
    print(f"Lấy G[{row}, indices{col}] (indices = {col}) = {val}")


tensor([[0.8070, 0.8423, 0.5213, 0.9339, 0.6564],
        [0.0478, 0.7200, 0.8971, 0.4940, 0.1073],
        [0.6347, 0.0592, 0.1178, 0.4894, 0.0511],
        [0.9146, 0.9934, 0.2037, 0.8570, 0.1141],
        [0.6272, 0.0866, 0.1914, 0.6328, 0.1711]])
tensor([[4],
        [3],
        [2],
        [1],
        [0]])
Shape của result: torch.Size([5, 1])
tensor([[0.6564],
        [0.4940],
        [0.1178],
        [0.9934],
        [0.6272]])
Lấy G[0, indices4] (indices = 4) = 0.6563822627067566
Lấy G[1, indices3] (indices = 3) = 0.49398642778396606
Lấy G[2, indices2] (indices = 2) = 0.1178242564201355
Lấy G[3, indices1] (indices = 1) = 0.9933950304985046
Lấy G[4, indices0] (indices = 0) = 0.6271790862083435


In [28]:


G = torch.tensor([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [1.1, 1.2, 1.3, 1.4, 1.5],
    [2.1, 2.2, 2.3, 2.4, 2.5],
    [3.1, 3.2, 3.3, 3.4, 3.5],
    [4.1, 4.2, 4.3, 4.4, 4.5]
])  # shape (5,5)

# Chỉ số hàng muốn lấy tại từng cột:
# Ví dụ cột 0 lấy hàng 0, cột 1 lấy hàng 1, ...
row_indices = torch.tensor([0, 1, 2, 3, 4])  # shape (5,)

# Tạo index tensor shape (5,5), mỗi cột đều lấy đúng chỉ số hàng mình cần:
# Mỗi cột lặp lại 5 lần cho đủ shape (5,5)
index = row_indices.unsqueeze(0).repeat(5, 1)  # shape (5,5)

# Thực hiện gather theo chiều 0 (hàng)
result = torch.gather(G, dim=0, index=index)

print("Tensor G:\n", G)
print("Index lấy phần tử theo hàng (dim=0):\n", index)
print("Kết quả gather:\n", result)

# Debug từng phần tử:
for i in range(result.shape[0]):  # 5 hàng của kết quả
    for j in range(result.shape[1]):  # 5 cột
        r = index[i, j].item()  # chỉ số hàng lấy
        val = G[r, j].item()
        print(f"Lấy G[{r},{j}] = {val} vào vị trí result[{i},{j}]")


Tensor G:
 tensor([[0.1000, 0.2000, 0.3000, 0.4000, 0.5000],
        [1.1000, 1.2000, 1.3000, 1.4000, 1.5000],
        [2.1000, 2.2000, 2.3000, 2.4000, 2.5000],
        [3.1000, 3.2000, 3.3000, 3.4000, 3.5000],
        [4.1000, 4.2000, 4.3000, 4.4000, 4.5000]])
Index lấy phần tử theo hàng (dim=0):
 tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])
Kết quả gather:
 tensor([[0.1000, 1.2000, 2.3000, 3.4000, 4.5000],
        [0.1000, 1.2000, 2.3000, 3.4000, 4.5000],
        [0.1000, 1.2000, 2.3000, 3.4000, 4.5000],
        [0.1000, 1.2000, 2.3000, 3.4000, 4.5000],
        [0.1000, 1.2000, 2.3000, 3.4000, 4.5000]])
Lấy G[0,0] = 0.10000000149011612 vào vị trí result[0,0]
Lấy G[1,1] = 1.2000000476837158 vào vị trí result[0,1]
Lấy G[2,2] = 2.299999952316284 vào vị trí result[0,2]
Lấy G[3,3] = 3.4000000953674316 vào vị trí result[0,3]
Lấy G[4,4] = 4.5 vào vị trí result[0,4]
Lấy G[0,0] = 0.10000000149011612 vào vị trí re

In [25]:


x = torch.tensor([1, 2, 3, 4, 5])
print("Original x:", x)
print("Shape:", x.shape)  # (5,)

x_unsq0 = x.unsqueeze(0)
print("\nAfter unsqueeze(0):")
print(x_unsq0)
print("Shape:", x_unsq0.shape)  # (1,5)

# Debug từng phần tử
for i in range(x_unsq0.shape[0]):
    for j in range(x_unsq0.shape[1]):
        print(f"x_unsq0[{i},{j}] = {x_unsq0[i,j]}")


Original x: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])

After unsqueeze(0):
tensor([[1, 2, 3, 4, 5]])
Shape: torch.Size([1, 5])
x_unsq0[0,0] = 1
x_unsq0[0,1] = 2
x_unsq0[0,2] = 3
x_unsq0[0,3] = 4
x_unsq0[0,4] = 5


In [26]:

x = torch.tensor([1, 2, 3, 4, 5])
print("Original x:", x)
print("Shape:", x.shape)  # (5,)

x_unsq1 = x.unsqueeze(1)
print("\nAfter unsqueeze(1):")
print(x_unsq1)
print("Shape:", x_unsq1.shape)  # (5,1)

# Debug từng phần tử
for i in range(x_unsq1.shape[0]):
    for j in range(x_unsq1.shape[1]):
        print(f"x_unsq1[{i},{j}] = {x_unsq1[i,j]}")


Original x: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])

After unsqueeze(1):
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Shape: torch.Size([5, 1])
x_unsq1[0,0] = 1
x_unsq1[1,0] = 2
x_unsq1[2,0] = 3
x_unsq1[3,0] = 4
x_unsq1[4,0] = 5


In [23]:


x = torch.tensor([1, 2, 3, 4, 5])
x_unsq1 = x.unsqueeze(1)
print("x_unsq1:", x_unsq1)
print("Shape:", x_unsq1.shape)  # (5,1)

x_sq = x_unsq1.squeeze(1)
print("\nAfter squeeze(1):")
print(x_sq)
print("Shape:", x_sq.shape)  # (5,)

# Debug từng phần tử
for i in range(x_sq.shape[0]):
    print(f"x_sq[{i}] = {x_sq[i]}")


x_unsq1: tensor([[1],
        [2],
        [3],
        [4],
        [5]])
Shape: torch.Size([5, 1])

After squeeze(1):
tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
x_sq[0] = 1
x_sq[1] = 2
x_sq[2] = 3
x_sq[3] = 4
x_sq[4] = 5


In [24]:


x2 = torch.arange(12)
print("Original x2:", x2)
print("Shape:", x2.shape)  # (12,)

x2_view = x2.view(3,4)
print("\nAfter view(3,4):")
print(x2_view)
print("Shape:", x2_view.shape)  # (3,4)

# Debug từng phần tử
for i in range(x2_view.shape[0]):
    for j in range(x2_view.shape[1]):
        print(f"x2_view[{i},{j}] = {x2_view[i,j]}")


Original x2: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])

After view(3,4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape: torch.Size([3, 4])
x2_view[0,0] = 0
x2_view[0,1] = 1
x2_view[0,2] = 2
x2_view[0,3] = 3
x2_view[1,0] = 4
x2_view[1,1] = 5
x2_view[1,2] = 6
x2_view[1,3] = 7
x2_view[2,0] = 8
x2_view[2,1] = 9
x2_view[2,2] = 10
x2_view[2,3] = 11


In [29]:
import numpy as np

G = np.array([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [1.1, 1.2, 1.3, 1.4, 1.5],
    [2.1, 2.2, 2.3, 2.4, 2.5],
    [3.1, 3.2, 3.3, 3.4, 3.5],
    [4.1, 4.2, 4.3, 4.4, 4.5]
])  # shape (5,5)

row_indices = np.array([0, 1, 2, 3, 4])  # chỉ số hàng theo từng cột
index = np.tile(row_indices, (5,1))      # shape (5,5)

# Lấy phần tử theo hàng (axis=0)
result = np.take_along_axis(G, index, axis=0)

print(result)


[[0.1 1.2 2.3 3.4 4.5]
 [0.1 1.2 2.3 3.4 4.5]
 [0.1 1.2 2.3 3.4 4.5]
 [0.1 1.2 2.3 3.4 4.5]
 [0.1 1.2 2.3 3.4 4.5]]


In [32]:
X = torch.randn(3,2,2)
print(X)
Y = torch.randn(3,2,2)
print(Y)
Z=torch.bmm(X,Y)
print(Z)

tensor([[[-0.6180, -0.6220],
         [ 1.8813,  2.2434]],

        [[-0.7582, -1.3416],
         [ 0.7986,  0.5521]],

        [[ 1.7307,  0.5397],
         [-1.2095, -1.6158]]])
tensor([[[-0.9713, -0.6848],
         [ 1.0216,  1.0604]],

        [[-0.6393, -0.1079],
         [-0.0938, -0.2658]],

        [[ 0.4425,  2.9501],
         [ 1.6762,  0.5799]]])
tensor([[[-0.0352, -0.2364],
         [ 0.4645,  1.0907]],

        [[ 0.6106,  0.4383],
         [-0.5624, -0.2329]],

        [[ 1.6705,  5.4185],
         [-3.2436, -4.5051]]])


In [36]:
sum_Z = Z.sum(dim=0)
sum_Z

tensor([[ 2.2459,  5.6205],
        [-3.3415, -3.6473]])

In [37]:
print(X.is_contiguous())


True


In [38]:
X_contig = X.contiguous()


In [41]:


# 1. Tạo tensor ban đầu
X = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print("X =")
print(X)
print("Is X contiguous?", X.is_contiguous())
print("X shape:", X.shape)
print("X strides:", X.stride())
print("="*50)

# 2. Transpose (không thay dữ liệu, chỉ thay cách nhìn)
X_T = X.t()
print("X.T =")
print(X_T)
print("Is X_T contiguous?", X_T.is_contiguous())
print("X_T shape:", X_T.shape)
print("X_T strides:", X_T.stride())  # bước nhảy khác với X
print("="*50)

# 3. Làm cho X_T thành contiguous (copy lại dữ liệu theo chiều mới)
X_T_contig = X_T.contiguous()
print("X_T_contig =")
print(X_T_contig)
print("Is X_T_contig contiguous?", X_T_contig.is_contiguous())
print("X_T_contig shape:", X_T_contig.shape)
print("X_T_contig strides:", X_T_contig.stride())


X =
tensor([[1, 2, 3],
        [4, 5, 6]])
Is X contiguous? True
X shape: torch.Size([2, 3])
X strides: (3, 1)
X.T =
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Is X_T contiguous? False
X_T shape: torch.Size([3, 2])
X_T strides: (1, 3)
X_T_contig =
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Is X_T_contig contiguous? True
X_T_contig shape: torch.Size([3, 2])
X_T_contig strides: (2, 1)
