In [1]:
import numpy as np

In [5]:
arr1 = np.array([2,3,4])
arr2 = np.array([5,5,7])
stacked_arr = np.stack((arr1,arr2),axis=0)

In [6]:
print(stacked_arr)

[[2 3 4]
 [5 5 7]]


In [7]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

print(matrix1+matrix2)

[[ 6  8]
 [10 12]]


In [8]:
matrix1= [[1,2],[3,4]]
matrix2 = [[5,6],[7,8]]
print(matrix1+matrix2)

[[1, 2], [3, 4], [5, 6], [7, 8]]


In [9]:
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

result = [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))]
          for i in range(len(matrix1))]

print(result)


[[6, 8], [10, 12]]


In [11]:
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

result = []
for row1, row2 in zip(matrix1, matrix2):
    print("row1:", row1)
    print("row2:", row2)
    row_result = []
    for a, b in zip(row1, row2):
        print(f"  a: {a}, b: {b}, a + b = {a + b}")
        row_result.append(a + b)
    result.append(row_result)

print("Final result:", result)


row1: [1, 2]
row2: [5, 6]
  a: 1, b: 5, a + b = 6
  a: 2, b: 6, a + b = 8
row1: [3, 4]
row2: [7, 8]
  a: 3, b: 7, a + b = 10
  a: 4, b: 8, a + b = 12
Final result: [[6, 8], [10, 12]]


In [13]:
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']

for index, (item1, item2) in enumerate(zip(list1, list2)):
    print(f"Index {index}: {item1} and {item2}")


Index 0: 1 and a
Index 1: 2 and b
Index 2: 3 and c


In [16]:
my_dict = {'name': 'Alice', 'age': 25, 'city': 'New York'}
print(my_dict)
# Lặp qua keys
for key in my_dict.keys():
    print(key)


{'name': 'Alice', 'age': 25, 'city': 'New York'}
name
age
city


In [17]:
my_dict = {'name': 'Alice', 'age': 25, 'city': 'New York'}

# Lặp qua key-value pairs
for key, value in my_dict.items():
    print(f"Key: {key}, Value: {value}")


Key: name, Value: Alice
Key: age, Value: 25
Key: city, Value: New York


In [23]:
# Định nghĩa Node
class Node:
    def __init__(self, data):
        self.data = data  # Dữ liệu của node
        self.next = None  # Con trỏ đến node tiếp theo

# Định nghĩa LinkedList
class LinkedList:
    def __init__(self):
        self.head = None  # Đầu danh sách (khởi tạo là None)

    # Thêm node vào cuối linked list
    def append(self, data):
        new_node = Node(data)
        if not self.head:  # Nếu danh sách rỗng
            self.head = new_node  # Đặt node mới làm đầu danh sách
        else:
            current = self.head
            while current.next:  # Duyệt đến node cuối
                current = current.next
            current.next = new_node  # Gắn node mới vào cuối danh sách

    # In toàn bộ linked list
    def print_list(self):
        current = self.head
        while current:  # Duyệt qua các node trong linked list
            print(current.data, end=" -> ")
            current = current.next
        print("None")

    # Thêm node vào đầu linked list
    def prepend(self, data):
        new_node = Node(data)
        new_node.next = self.head
        self.head = new_node

    # Xóa node đầu tiên có giá trị cụ thể
    def delete(self, key):
        current = self.head
        if current and current.data == key:
            self.head = current.next
            current = None
            return

        prev = None
        while current and current.data != key:
            prev = current
            current = current.next

        if current is None:
            return  # Không tìm thấy key

        prev.next = current.next
        current = None

# Sử dụng LinkedList
ll = LinkedList()
ll.append(1)
ll.append(2)
ll.append(3)
ll.append(4)

ll.print_list()  # In ra: 1 -> 2 -> 3 -> 4 -> None

ll.prepend(0)  # Thêm 0 vào đầu danh sách
ll.print_list()  # In ra: 0 -> 1 -> 2 -> 3 -> 4 -> None

ll.delete(3)  # Xóa node có giá trị 3
ll.print_list()  # In ra: 0 -> 1 -> 2 -> 4 -> None


1 -> 2 -> 3 -> 4 -> None
0 -> 1 -> 2 -> 3 -> 4 -> None
0 -> 1 -> 2 -> 4 -> None


In [25]:
array = np.array([1,2,3,4,5,6])
result = np.where(array>3 , "True","False")
print(result)

['False' 'False' 'False' 'True' 'True' 'True']


In [ ]:
bg_image = cv2.i